### ISSUE TITLE
Building does not verify gonixutils version

### ISSUE THREAD

**Issue by clintonskitson** [emccode/libstorage#10]
I ran into an issue building libStorage for testing today because of a stale version of `gonixutils` that was present. 

```
dicey1:libstorage clintonkitson$ make deps
go build -o /Users/clintonkitson/go/bin/printf-gnix github.com/akutz/gnixutils/cli/printf
can't load package: package github.com/akutz/gnixutils/cli/printf: cannot find package "github.com/akutz/gnixutils/cli/printf" in any of:
	/usr/local/go/src/github.com/akutz/gnixutils/cli/printf (from $GOROOT)
	/Users/clintonkitson/go/src/github.com/akutz/gnixutils/cli/printf (from $GOPATH)
```

This was fixed by removing the old version with `rm -Rf $GOPATH/src/github.com/akutz/gonixutils` and re-running `make deps`.

**Comment by akutz** [comment]
Hi @clintonskitson, 

Thanks for filing this. OOC, why invoke `make deps` directly? Is there an issue using `make install` or one of its cross variants? I think I fixed the issue of deps not working for cross builds.

**Comment by clintonskitson** [comment]
In troubleshooting it, I was just replicating what I saw in the Travis-CI log to make sure I aligned against a known working method.

**Comment by akutz** [comment]
Hi @clintonskitson,

Understood. Makes sense. I should set Travis up to dogfood the fix.
