### ISSUE TITLE
Does the REST API(in libstorage.apib) exposed in rexray ? 

### ISSUE THREAD

**Issue by pacoxu** [emccode/libstorage#115]
I tried rexray 7979 port and cannot access those APIs.

Is there a way to use those REST API directly in my docker environment?

**Comment by akutz** [comment]
Hi @pacoxu,

There is, and if you're available for a Google hangout I'd be more than happy to show you how to do so. REX-Ray starts the libStorage server on a UNIX socket by default, so it's not externally accessible or by TCP unless configured specifically for that purpose.

**Comment by pacoxu** [comment]
Hi @akutz

Do you mean the socket in ./run/docker/plugins/rexray.sock ?

How could I check it directly?

I tried to 
	curl —insecure http://127.0.0.1:7979/ 
	curl —insecure http://127.0.0.1:7979/volumes ? which not work.


By the way,  I tried to change 127.0.0.1 to its IP and failed. I want to test it in my pc.

REXRAY_MODULES_DEFAULT-ADMIN_HOST=tcp://127.0.0.1:7979
REXRAY_HOST=tcp://:7979

[root@scale132 /]# export REXRAY_MODULES_DEFAULT-ADMIN_HOST=tcp://192.168.1.132:7979
bash: export: `REXRAY_MODULES_DEFAULT-ADMIN_HOST=tcp://192.168.1.132:7979':

Thanks.

**Comment by akutz** [comment]
Hi @pacoxu,

It does not refer to that socket, no. And regardless, the syntax for communicating with a UNIX socket via curl is `curl --unix-socket PATH.sock http:/URL`. The variables `PATH` and `URL` should be replaced with the path to the UNIX socket and path to the API resource, respectively. 

The socket on which the embedded libStorage server is started is randomly generated via a temp file method, so I cannot tell you what it is offhand. However, you can run REX-Ray with at least the `-l info` option to see the log at INFO level, and it will print the socket path in there. For example:

### Find the libStorage UNIX socket
```
./rexray start -f -l info

                          ⌐▄Q▓▄Ç▓▄,▄_
                         Σ▄▓▓▓▓▓▓▓▓▓▓▄π
                       ╒▓▓▌▓▓▓▓▓▓▓▓▓▓▀▓▄▄.
                    ,_▄▀▓▓ ▓▓ ▓▓▓▓▓▓▓▓▓▓▓█
                   │▄▓▓ _▓▓▓▓▓▓▓▓▓┌▓▓▓▓▓█
                  _J┤▓▓▓▓▓▓▓▓▓▓▓▓▓├█▓█▓▀Γ
            ,▄▓▓▓▓▓▓^██▓▓▓▓▓▓▓▓▓▓▓▓▄▀▄▄▓▓Ω▄
            F▌▓▌█ⁿⁿⁿ  ⁿ└▀ⁿ██▓▀▀▀▀▀▀▀▀▀▀▌▓▓▓▌
             'ⁿ_  ,▄▄▄▄▄▄▄▄▄█_▄▄▄▄▄▄▄▄▄ⁿ▀~██
               Γ  ├▓▓▓▓▓█▀ⁿ█▌▓Ω]█▓▓▓▓▓▓ ├▓
               │  ├▓▓▓▓▓▌≡,__▄▓▓▓█▓▓▓▓▓ ╞█~   Y,┐
               ╞  ├▓▓▓▓▓▄▄__^^▓▓▓▌▓▓▓▓▓  ▓   /▓▓▓
                  ├▓▓▓▓▓▓▓▄▄═▄▓▓▓▓▓▓▓▓▓  π ⌐▄▓▓█║n
                _ ├▓▓▓▓▓▓▓▓▓~▓▓▓▓▓▓▓▓▓▓  ▄4▄▓▓▓██
                µ ├▓▓▓▓█▀█▓▓_▓▓███▓▓▓▓▓  ▓▓▓▓▓Ω4
                µ ├▓▀▀L   └ⁿ  ▀   ▀ ▓▓█w ▓▓▓▀ìⁿ
                ⌐ ├_                τ▀▓  Σ⌐└
                ~ ├▓▓  ▄  _     ╒  ┌▄▓▓  Γ
                  ├▓▓▓▌█═┴▓▄╒▀▄_▄▌═¢▓▓▓  ╚
               ⌠  ├▓▓▓▓▓ⁿ▄▓▓▓▓▓▓▓┐▄▓▓▓▓  └
               Ω_.└██▓▀ⁿÇⁿ▀▀▀▀▀▀█≡▀▀▀▀▀   µ
               ⁿ  .▄▄▓▓▓▓▄▄┌ ╖__▓_▄▄▄▄▄*Oⁿ
                 û▌├▓█▓▓▓██ⁿ ¡▓▓▓▓▓▓▓▓█▓╪
                 ╙Ω▀█ ▓██ⁿ    └█▀██▀▓█├█Å
                     ⁿⁿ             ⁿ ⁿ^
:::::::..  .,::::::    .,::      .::::::::..    :::.  .-:.     ::-.
;;;;'';;;; ;;;;''''    ';;;,  .,;; ;;;;'';;;;   ;;';;  ';;.   ;;;;'
 [[[,/[[['  [[cccc       '[[,,[['   [[[,/[[['  ,[[ '[[,  '[[,[[['
 $$$$$$c    $$""""        Y$$$Pcccc $$$$$$c   c$$$cc$$$c   c$$"
 888b "88bo,888oo,__    oP"''"Yo,   888b "88bo,888   888,,8P"'
 MMMM   "W" """"YUMMM,m"       "Mm, MMMM   "W" YMM   ""'mM"

Binary: /Users/akutz/Projects/go/bin/rexray
SemVer: 0.4.0-rc1
OsArch: linux_amd64
Branch: master
Commit: 4cff7bd5f62279b2f2f5ebc9acf432c2daa6e762
Formed: 2016/05/09

INFO[0000] created pid file, pid=20250                  
INFO[0000] initializing server                           server=big-horn-lb
INFO[0000] configured endpoint                           address=unix:///tmp/784790110.sock endpoint=localhost server=big-horn-lb
```

In the above example the libStorage server is running on the socket file `/tmp/784790110.sock`. I can then use curl to list the root resources available on that server:

### Using `curl` with the libStorage UNIX socket
```
$ curl --unix-socket /tmp/784790110.sock http:/
curl: (7) Couldn't connect to server
```

Oops! Keep in mind that the socket file is created with permissions so that only the user whom creates it can read it, in this case, `root`. It's so only the REX-Ray process can communicate with the libStorage server (by default). Let's try this again with `sudo`:

### Using `sudo curl` with the libStorage UNIX socket
```
$ sudo curl --unix-socket /tmp/784790110.sock http:/
[
  "http://http/executors",
  "http://http/services",
  "http://http/snapshots",
  "http://http/tasks",
  "http://http/volumes"
]
```

Or to get a list of volumes:

### Listing libStorage volumes with `curl`
```
$ sudo curl --unix-socket /tmp/784790110.sock http:/volumes
{
  "vfs": {
    "vfs-000": {
      "availabilityZone": "us",
      "iops": 1000,
      "name": "Volume 000",
      "size": 40960,
      "id": "vfs-000",
      "type": ""
    }
  }
}
```

Or to create a volume:

### Creating a libStorage volume with `curl`
```
$ sudo curl --unix-socket /tmp/784790110.sock http:/volumes/vfs -H "Content-Type: application/json" -X POST -d '{"name":"Volume for 徐俊杰", "size": 40960, "iops": 100, "availabilityZone":"US-NW"}''
{
  "availabilityZone": "US-NW",
  "iops": 100,
  "name": "Volume for 徐俊杰",
  "size": 40960,
  "id": "vfs-001",
  "type": ""
}
```

And then to inspect the new volume:

### Inspecting a libStorage volume with `curl`
```
$ sudo curl --unix-socket /tmp/784790110.sock http:/volumes/vfs/vfs-001
{
  "availabilityZone": "US-NW",
  "iops": 100,
  "name": "Volume for 徐俊杰",
  "size": 40960,
  "id": "vfs-001",
  "type": ""
}
```

Or to find the same volume by name instead of by ID:

### Finding a libStorage volume by name with `curl`
```
$ sudo curl --unix-socket /tmp/784790110.sock "http:/volumes?filter=(name%3DVolume%20for%20徐俊杰)"
{
  "vfs": {
    "vfs-001": {
      "availabilityZone": "US-NW",
      "iops": 100,
      "name": "Volume for 徐俊杰",
      "size": 40960,
      "id": "vfs-001",
      "type": ""
    }
  }
}
```

You can also specify, in the configuration file, the address REX-Ray *should* use when starting an embedded libStorage server. 

### A simple REX-Ray config file
```
$ cat rexray.config.yaml
rexray:
  libstorage:
    host: tcp://127.0.0.1:7980
    embedded: true
```

Then specify that file when starting REX-Ray:

### Starting REX-Ray's embedded libStorage server on specific address
```
# ./rexray start -f -l info -c rexray.config.yaml 

                          ⌐▄Q▓▄Ç▓▄,▄_
                         Σ▄▓▓▓▓▓▓▓▓▓▓▄π
                       ╒▓▓▌▓▓▓▓▓▓▓▓▓▓▀▓▄▄.
                    ,_▄▀▓▓ ▓▓ ▓▓▓▓▓▓▓▓▓▓▓█
                   │▄▓▓ _▓▓▓▓▓▓▓▓▓┌▓▓▓▓▓█
                  _J┤▓▓▓▓▓▓▓▓▓▓▓▓▓├█▓█▓▀Γ
            ,▄▓▓▓▓▓▓^██▓▓▓▓▓▓▓▓▓▓▓▓▄▀▄▄▓▓Ω▄
            F▌▓▌█ⁿⁿⁿ  ⁿ└▀ⁿ██▓▀▀▀▀▀▀▀▀▀▀▌▓▓▓▌
             'ⁿ_  ,▄▄▄▄▄▄▄▄▄█_▄▄▄▄▄▄▄▄▄ⁿ▀~██
               Γ  ├▓▓▓▓▓█▀ⁿ█▌▓Ω]█▓▓▓▓▓▓ ├▓
               │  ├▓▓▓▓▓▌≡,__▄▓▓▓█▓▓▓▓▓ ╞█~   Y,┐
               ╞  ├▓▓▓▓▓▄▄__^^▓▓▓▌▓▓▓▓▓  ▓   /▓▓▓
                  ├▓▓▓▓▓▓▓▄▄═▄▓▓▓▓▓▓▓▓▓  π ⌐▄▓▓█║n
                _ ├▓▓▓▓▓▓▓▓▓~▓▓▓▓▓▓▓▓▓▓  ▄4▄▓▓▓██
                µ ├▓▓▓▓█▀█▓▓_▓▓███▓▓▓▓▓  ▓▓▓▓▓Ω4
                µ ├▓▀▀L   └ⁿ  ▀   ▀ ▓▓█w ▓▓▓▀ìⁿ
                ⌐ ├_                τ▀▓  Σ⌐└
                ~ ├▓▓  ▄  _     ╒  ┌▄▓▓  Γ
                  ├▓▓▓▌█═┴▓▄╒▀▄_▄▌═¢▓▓▓  ╚
               ⌠  ├▓▓▓▓▓ⁿ▄▓▓▓▓▓▓▓┐▄▓▓▓▓  └
               Ω_.└██▓▀ⁿÇⁿ▀▀▀▀▀▀█≡▀▀▀▀▀   µ
               ⁿ  .▄▄▓▓▓▓▄▄┌ ╖__▓_▄▄▄▄▄*Oⁿ
                 û▌├▓█▓▓▓██ⁿ ¡▓▓▓▓▓▓▓▓█▓╪
                 ╙Ω▀█ ▓██ⁿ    └█▀██▀▓█├█Å
                     ⁿⁿ             ⁿ ⁿ^
:::::::..  .,::::::    .,::      .::::::::..    :::.  .-:.     ::-.
;;;;'';;;; ;;;;''''    ';;;,  .,;; ;;;;'';;;;   ;;';;  ';;.   ;;;;'
 [[[,/[[['  [[cccc       '[[,,[['   [[[,/[[['  ,[[ '[[,  '[[,[[['
 $$$$$$c    $$""""        Y$$$Pcccc $$$$$$c   c$$$cc$$$c   c$$"
 888b "88bo,888oo,__    oP"''"Yo,   888b "88bo,888   888,,8P"'
 MMMM   "W" """"YUMMM,m"       "Mm, MMMM   "W" YMM   ""'mM"

Binary: /Users/akutz/Projects/go/bin/rexray
SemVer: 0.4.0-rc1
OsArch: linux_amd64
Branch: master
Commit: 4cff7bd5f62279b2f2f5ebc9acf432c2daa6e762
Formed: 2016/05/09

INFO[0000] created pid file, pid=20903                  
INFO[0000] initializing server                           server=candle-edge-tn
INFO[0000] configured endpoint                           address=tcp://127.0.0.1:7980 endpoint=localhost server=candle-edge-tn
INFO[0000] server created                                server=candle-edge-tn
```

In the log above you can see the address is `127.0.0.1:7980`. We can repeat the same `curl` examples above, but with the TCP address instead:

### Finding a libStorage volume by name with `curl` using TCP
```
$ sudo curl "http://127.0.0.1:7980/volumes?filter=(name%3DVolume%20for%20徐俊杰)"
{
  "vfs": {
    "vfs-001": {
      "availabilityZone": "US-NW",
      "iops": 100,
      "name": "Volume for 徐俊杰s",
      "size": 40960,
      "id": "vfs-001",
      "type": ""
    }
  }
}
```

I hope this helps. Please let me know if you have any more questions!

**Comment by pacoxu** [comment]
Thanks a lot for your detailed response. I am using 0.3.3, and the libstorage host configuration seems not work and the log is different with your example with rexray 0.4.0-rc1. 

[root@scale132 ~]# cat /etc/rexray/rexray.config.yaml
rexray:
  logLevel: warn
  storageDrivers:
  - scaleio
  docker:
    size: 1
  libstorage:
    host: tcp://127.0.0.1:7980
    embedded: true
scaleio:
  endpoint: http:/
------------------
rexray service start -f -l info -c rexray.config.yaml

                          ⌐▄Q▓▄Ç▓▄,▄_
                         Σ▄▓▓▓▓▓▓▓▓▓▓▄π
                       ╒▓▓▌▓▓▓▓▓▓▓▓▓▓▀▓▄▄.
                    ,_▄▀▓▓ ▓▓ ▓▓▓▓▓▓▓▓▓▓▓█
                   │▄▓▓ _▓▓▓▓▓▓▓▓▓┌▓▓▓▓▓█
                  _J┤▓▓▓▓▓▓▓▓▓▓▓▓▓├█▓█▓▀Γ
            ,▄▓▓▓▓▓▓^██▓▓▓▓▓▓▓▓▓▓▓▓▄▀▄▄▓▓Ω▄
            F▌▓▌█ⁿⁿⁿ  ⁿ└▀ⁿ██▓▀▀▀▀▀▀▀▀▀▀▌▓▓▓▌
             'ⁿ_  ,▄▄▄▄▄▄▄▄▄█_▄▄▄▄▄▄▄▄▄ⁿ▀~██
               Γ  ├▓▓▓▓▓█▀ⁿ█▌▓Ω]█▓▓▓▓▓▓ ├▓
               │  ├▓▓▓▓▓▌≡,__▄▓▓▓█▓▓▓▓▓ ╞█~   Y,┐
               ╞  ├▓▓▓▓▓▄▄__^^▓▓▓▌▓▓▓▓▓  ▓   /▓▓▓
                  ├▓▓▓▓▓▓▓▄▄═▄▓▓▓▓▓▓▓▓▓  π ⌐▄▓▓█║n
                _ ├▓▓▓▓▓▓▓▓▓~▓▓▓▓▓▓▓▓▓▓  ▄4▄▓▓▓██
                µ ├▓▓▓▓█▀█▓▓_▓▓███▓▓▓▓▓  ▓▓▓▓▓Ω4
                µ ├▓▀▀L   └ⁿ  ▀   ▀ ▓▓█w ▓▓▓▀ìⁿ
                ⌐ ├_                τ▀▓  Σ⌐└
                ~ ├▓▓  ▄  _     ╒  ┌▄▓▓  Γ
                  ├▓▓▓▌█═┴▓▄╒▀▄_▄▌═¢▓▓▓  ╚
               ⌠  ├▓▓▓▓▓ⁿ▄▓▓▓▓▓▓▓┐▄▓▓▓▓  └
               Ω_.└██▓▀ⁿÇⁿ▀▀▀▀▀▀█≡▀▀▀▀▀   µ
               ⁿ  .▄▄▓▓▓▓▄▄┌ ╖__▓_▄▄▄▄▄*Oⁿ
                 û▌├▓█▓▓▓██ⁿ ¡▓▓▓▓▓▓▓▓█▓╪
                 ╙Ω▀█ ▓██ⁿ    └█▀██▀▓█├█Å
                     ⁿⁿ             ⁿ ⁿ^
:::::::..  .,::::::    .,::      .::::::::..    :::.  .-:.     ::-.
;;;;'';;;; ;;;;''''    ';;;,  .,;; ;;;;'';;;;   ;;';;  ';;.   ;;;;'
 [[[,/[[['  [[cccc       '[[,,[['   [[[,/[[['  ,[[ '[[,  '[[,[[['
 $$$$$$c    $$""""        Y$$$Pcccc $$$$$$c   c$$$cc$$$c   c$$"
 888b "88bo,888oo,__    oP"''"Yo,   888b "88bo,888   888,,8P"'
 MMMM   "W" """"YUMMM,m"       "Mm, MMMM   "W" YMM   ""'mM"

Binary: /usr/bin/rexray
SemVer: 0.3.3
OsArch: Linux-x86_64
Branch: v0.3.3
Commit: b30fb870b5b94cd8368824460ad020bfcf20be3a
Formed: Fri, 22 Apr 2016 03:41:36 CST

INFO[0000] created pid file, pid=6228
INFO[0000] created new mod config                        addr=tcp://127.0.0.1:7979 desc=The default admin module. name=default-admin type=admin
INFO[0000] created new mod config                        addr=unix:///run/docker/plugins/rexray.sock desc=The default docker module. name=default-docker type=docker
INFO[0000] initialized module instance                   address=tcp://127.0.0.1:7979 name=default-admin typeName=admin
INFO[0000] initialized module instance                   address=unix:///run/docker/plugins/rexray.sock name=default-docker typeName=docker
INFO[0000] started module                                address=tcp://127.0.0.1:7979 name=default-admin typeName=admin
INFO[0000] [linux]
INFO[0000] [docker]
INFO[0000] scaleio


Then, I tried the RPM installer package under https://dl.bintray.com/emccode/rexray/staged/0.4.0-rc1/

I uninstall the 0.3.3 and downlod the 0.4.0-rc1.
[root@scale132 ~]# rexray uninstall
[root@scale132 ~]# wget https://dl.bintray.com/emccode/rexray/staged/0.4.0-rc1/rexray-0.4.0+rc1-1.x86_64.rpm
[root@scale132 ~]# rpm -U rexray-0.4.0+rc1-1.x86_64.rpm

`
Binary: /usr/bin/rexray
SemVer: 0.4.0-rc1
OsArch: Linux-x86_64
Branch: v0.4.0-rc1
Commit: 4cff7bd5f62279b2f2f5ebc9acf432c2daa6e762
Formed: Tue, 10 May 2016 11:54:44 CST

INFO[0000] created pid file, pid=4900
INFO[0000] initializing server                           server=lapis-yak-it
INFO[0000] configured endpoint                           address=unix:///tmp/794435227.sock endpoint=localhost server=lapis-yak-it
INFO[0000] server created                                server=lapis-yak-it
INFO[0000] initialized endpoints                         server=lapis-yak-it
INFO[0000] initializing server services                  server=lapis-yak-it
ERRO[0000] default module(s) failed to initialize
INFO[0000] service sent registered modules start signals
ERRO[0000] service initialized failed
INFO[0000] invalid forma                                 configKey=libstorage.server.services obj=<nil>
`


Is this build not a stable one or is it a bug? Hence, I should wait for 0.4 release?

Thanks

**Comment by akutz** [comment]
Hi @pacoxu,

I apologize, I thought you were attempting to use the 0.4.0 RC as I don't believe @clintonskitson or I have ever advertised the REST APIs  as any type of externally accessible feature in the previous versions. @clintonskitson, care to comment? The 0.3.3 is quite stable, I just misunderstood.

Moving forward, you *should* be able to access the REST API exposed via RR's Docker Volume Endpoint using similar `curl` commands as above. For reference on what calls you can use, please see the [Docker Volume Plug-in documentation](https://docs.docker.com/engine/extend/plugins_volume/).

The first step is to start REX-Ray as a service like you normally would. Then you're able to access the Docker Volume Plug-in endpoint exposed by REX-Ray:

### List Volumes via `REX-Ray`'s Docker Volume Endpoint
```
$ sudo curl --unix-socket /run/docker/plugins/rexray.sock \
       -H "Content-Type: application/json" \
       -X POST \
       -d@- \
       http:/VolumeDriver.List << EOF
{}
EOF
{"Volumes":[{"Name":"Volume for 徐俊杰","Mountpoint":""},{"Name":"Volume for 徐俊杰","Mountpoint":""},{"Name":"Volume for 徐俊杰","Mountpoint":""}]}
```

### Getting a Volume via `REX-Ray`s Docker Volume Endpoint
```
sudo curl --unix-socket /run/docker/plugins/rexray.sock \
     -H "Content-Type: application/json" \
     -X POST \
     -d@- \
     http:/VolumeDriver.Get << EOF
{
  "Name": "Volume for 徐俊杰"
}
EOF
{"Volume":{"Name":"Volume for 徐俊杰","Mountpoint":""}}
```

**Comment by akutz** [comment]
Hi @pacoxu,

It just occurred to me why I thought you were using REX-Ray 0.4.0 RC1 -- this is the libStorage issue tracker, and libStorage is irrelevant to REX-Ray prior to 0.4.0 RC1. I'm going to close this issue. If you have further questions about REX-Ray, please use the REX-Ray issue tracker.

**Comment by pacoxu** [comment]
Hi @akutz  

Thanks a lot for your quick and detailed explanation.  OK, I will use Rex-ray issue to track if I have further problems. Thanks.

Best regard,
Paco
