### ISSUE TITLE
scaleio - libstorage still depends on having scaleio sdc installed

### ISSUE THREAD

**Issue by cduchesne** [emccode/libstorage#152]
polly exits with status 1 if scaleio sdc isn't installed
```
# polly service status
● polly.service - polly
   Loaded: loaded (/etc/systemd/system/polly.service; static; vendor preset: disabled)
   Active: inactive (dead)

May 23 11:31:11 sol polly[19248]: time="2016-05-23T11:31:11-07:00" level=error msg="libstorage.embedded=false"
May 23 11:31:11 sol polly[19248]: time="2016-05-23T11:31:11-07:00" level=error msg="libstorage.executor.disabledownload=false"
May 23 11:31:11 sol polly[19248]: time="2016-05-23T11:31:11-07:00" level=error msg="isilon.datasubnet="
May 23 11:31:11 sol polly[19248]: time="2016-05-23T11:31:11-07:00" level=error msg="scaleio=map[apiVersion:2.0 insecure:true userName:admin password:sCaleIO2016 systemName:scaleio protectio
May 23 11:31:11 sol polly[19248]: time="2016-05-23T11:31:11-07:00" level=error msg="libstorage.integration.volume.operations.create.default.size=16"
May 23 11:31:11 sol polly[19248]: time="2016-05-23T11:31:11-07:00" level=error msg="libstorage.integration.volume.operations.create.default.fstype=ext4"
May 23 11:31:11 sol polly[19248]: time="2016-05-23T11:31:11-07:00" level=error msg="libstorage.logging.stdout="
May 23 11:31:11 sol polly[19248]: time="2016-05-23T11:31:11-07:00" level=error msg="libstorage.logging.httprequests=false"
May 23 11:31:11 sol polly[19248]: time="2016-05-23T11:31:11-07:00" level=error msg="error dialing libStorage service" host="tcp://localhost:7980" inner="exit status 1"
May 23 11:31:11 sol polly[19248]: time="2016-05-23T11:31:11-07:00" level=error msg="service initialization failed" error.host="tcp://localhost:7980" error.inner.Stderr=[]
```

**Comment by clintonskitson** [comment]
@akutz This is happens when the Polly (libstorage server/client) is running on a system that has not been installed as an SDC. I wonder if this could be related to https://github.com/emccode/libstorage/issues/151.

This doesn't sound exactly the same, but in terms of the instanceID validation, it could be similar. Are we missing the correct erroring here to get us the right verbosity?

**Comment by akutz** [comment]
Hi @clintonskitson,

Well, debugging is certainly not enabled here, and that would help. Could someone enable debug logging and reproduce the error?

Please see the libStorage [documentation section on adjusting logging](http://libstorage.readthedocs.io/en/v0.1.0-docs/user-guide/config/#logging) or simply set this environment variable - `export LIBSTORAGE_LOGGING_LEVEL=debug`.

**Comment by akutz** [comment]
Also, based on the issue filed above, it appears the example is using SystemD to show logging. Can the example be reproduced outside SystemD as SystemD sometimes decides to omit what it considers redundant log information?

**Comment by clintonskitson** [comment]
Closing out this thread. The updated configuration to address the scenario where clients can be of type `integration` or `controller`.

```
libstorage:
  client:
    type: controller
```
