### ISSUE TITLE
Volume.MountPoint should be populated after a mount operation

### ISSUE THREAD

**Issue by vladimirvivien** [emccode/libstorage#174]
Upon success, `libstorage/client.Integration().Mount()` returns a `mountPoint string`, a pointer to struct `libstorage/api/types.Volume`, and an `error`.  It would be nice if field `Volume.MountPoint()`  was pre-populated with the mount point value as well.

**Comment by clintonskitson** [comment]
@vladimirvivien Are you referencing that the `MountPoint()` method is not returning the expected field? I am not clear and what you are describing here.

**Comment by vladimirvivien** [comment]
@clintonskitson Yes, correct. `Volume.MountPoint()` is nil.

**Comment by akutz** [comment]
@clintonskitson and I just talked about this, we're going to update the MountPoint on the client side during a Mount op to avoid having to do a second round-trip to reinspect the volume.
