### ISSUE TITLE
Storage Controller PortCount = 1, will cause errors during device attachment (virtualbox,fedora)

### ISSUE THREAD

**Issue by vladimirvivien** [emccode/libstorage#196]
When a virtual machine has its port count set to 1 (maxportcount) in virtualbox, it causes enumeration issues when calculating the next available port for device attachment with error `The port and/or device parameter are out of range: port=1 (must be in range [0, 0]), device=0 (must be in range [0, 0]) (0x80070057)` (see the full error below).  The issue is possibly related to this method https://github.com/clintonskitson/go-virtualboxclient/blob/feature/dockerdriver/virtualboxclient/storage_controller.go#L82 which returns next available port.  This code works ok when the portcount is set to a number larger than available number used.

### Error
```
Jun 08 21:30:47 kubernetes-node-1 polly[28860]: time="2016-06-08T21:30:47Z" level=error msg="error attaching volume" host="tcp://:7981" inner="VirtualBox error: rc=0x80070057 The port and/or device parameter are out of range: port=1 (must be in range [0, 0]), device=0 (must be in range [0, 0]) (0x80070057)" provider=virtualbox route=volumeAttach server=bronze-back-gp time=1465421447 tls=false txCR=1465421446 txID=8a68dcb2-9714-486b-5964-5af75ee68ff0 volumeID=aa619c4e-d77c-4d66-b743-5f8f8644432c
```
### libStorage Config
```
<Polymorphic Storage Scheduling>
Polly
----------
Binary: /usr/bin/polly
SemVer: 0.1.1-dev+7
OsArch: Linux-x86_64
Branch: master
Commit: aa90964ce840c04e83b577ce7b1010b1a2efa317
Formed: Thu, 02 Jun 2016 15:20:44 UTC

libStorage
----------
SemVer: ..
OsArch: Linux-x86_64
Branch: master
Commit: bb9b9477e65ae23c035dc78096e8870c306b7112
Formed: Thu, 02 Jun 2016 15:19:47 UTC
```

### Docker Config
```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-24.gitf476348.fc23.x86_64
 Go version:      go1.5.4
 Git commit:      f476348/1.10.3
 Built:
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-24.gitf476348.fc23.x86_64
 Go version:      go1.5.4
 Git commit:      f476348/1.10.3
 Built:
 OS/Arch:         linux/amd64
```

Vagrant Config
```
Installed Version: 1.8.1
Latest Version: 1.8.1
```

**Comment by akutz** [comment]
Hi @vladimirvivien,

Setting the port count to > 0 is a [documented requirement](http://libstorage.readthedocs.io/en/latest/user-guide/storage-providers/#virtualbox).

**Comment by frjaraur** [comment]
I still have this error even if port is set 
<StorageControllers>
      <StorageController name="SATA" type="AHCI" PortCount="30" useHostIOCache="true" Bootable="true" IDE0MasterEmulationPort="0" IDE0SlaveEmulationPort="1" IDE1MasterEmulationPort="2" IDE1SlaveEmulationPort="3">
        <AttachedDevice type="HardDisk" hotpluggable="false" port="0" device="0">
          <Image uuid="{4cecf893-42dd-45a4-aa22-17d9619d3235}"/>
        </AttachedDevice>
        <AttachedDevice passthrough="false" type="DVD" hotpluggable="false" port="1" device="0"/>
      </StorageController>
    </StorageControllers>
I still get errors on mount and can not mount any rexray volumes
time="2017-02-24T13:13:32+01:00" level=error msg="/VolumeDriver.Get: error getting volume" error.resourceID=test2 host="unix:///var/run/libstorage/892335787.sock" time=1487938412258 
time="2017-02-24T13:13:49+01:00" level=error msg="error attaching volume" host="unix:///var/run/libstorage/892335787.sock" inner="VirtualBox error: rc=0x80070057 The port and/or device parameter are out of range: port=1 (must be in range [0, 0]), device=0 (must be in range [0, 0]) (0x80070057)" instanceID="virtualbox=a8a0533b-fd63-4ebe-a2d9-a6cd470e2bb9" provider=virtualbox route=volumeAttach server=storm-shoulder-ve service=virtualbox storageDriver=virtualbox task=0 time=1487938429217 tls=false txCR=1487938428 txID=23f52787-2521-47ba-5a7a-cdf5311475fb volumeID=1e6be105-32fa-447f-b7ed-903e081f4713 
time="2017-02-24T13:13:49+01:00" level=error msg="error attaching volume" host="unix:///var/run/libstorage/892335787.sock" inner="VirtualBox error: rc=0x80070057 The port and/or device parameter are out of range: port=1 (must be in range [0, 0]), device=0 (must be in range [0, 0]) (0x80070057)" provider=virtualbox route=volumeAttach server=storm-shoulder-ve time=1487938429217 tls=false txCR=1487938428 txID=23f52787-2521-47ba-5a7a-cdf5311475fb volumeID=1e6be105-32fa-447f-b7ed-903e081f4713 
time="2017-02-24T13:13:49+01:00" level=error msg="/VolumeDriver.Mount: error mounting volume" error.inner.inner.XMLName=map[Space:http://schemas.xmlsoap.org/soap/envelope/ Local:Fault] error.inner.inner.Code="SOAP-ENV:Client" error.inner.inner.String="VirtualBox error: rc=0x80070057 The port and/or device parameter are out of range: port=1 (must be in range [0, 0]), device=0 (must be in range [0, 0]) (0x80070057)" error.inner.inner.Actor= error.inner.inner.Detail= error.status=500 error.inner.provider=virtualbox error.inner.volumeID=1e6be105-32fa-447f-b7ed-903e081f4713 host="unix:///var/run/libstorage/892335787.sock" time=1487938429219
