### ISSUE TITLE
Add CoprHD Driver

### ISSUE THREAD

**Issue by victorock** [emccode/libstorage#206]
Hello,
What if the libStorage could support CoprHD?
The idea behind is to extend volume driver supportability of rex-ray to support CoprHD.

Sincerely,
Victor da Costa

**Comment by akutz** [comment]
What If? indeed!

![image](https://cloud.githubusercontent.com/assets/101085/16206364/b6800440-36ed-11e6-94fb-d9f8124f1bb9.png)

:)

**Comment by victorock** [comment]
Go Library for CoprHD: https://godoc.org/github.com/ModelRocket/coprhd

**Comment by clintonskitson** [comment]
Thanks for the heads up Victor.

**Comment by victorock** [comment]
Currently working in the GoCoprHD library: https://github.com/victorock/gocoprhd/tree/dev

**Comment by victorock** [comment]
Seem that there is no plan to develop this driver, since it is not even tagged as feature.

**Comment by victorock** [comment]
Official Container integration and support is available through Flocker: https://coprhd.atlassian.net/wiki/display/COP/CoprHD+and+Flocker+Integration
