### ISSUE TITLE
Review benchmark performance of integrator client

### ISSUE THREAD

**Issue by clintonskitson** [emccode/libstorage#212]
This is a placeholder to review the integrator client performance versus the previous REX-Ray 0.3.3 build. There does seem to be a measurable % increase in time to process requests that include executor operations.

**Comment by akutz** [comment]
Good call. I'll set up some timings

**Comment by akutz** [comment]
Hi @clintonskitson,

I believe this issue can be closed thanks to #218, #224, and #225. @cduchesne, do you agree? I'm not sure we ever had any other reason to think the executor was a culprit other than just initially taking educated-WAG before digging into the code to find out what was happening.

**Comment by clintonskitson** [comment]
It feels like we are where it needs to be now.

**Comment by cduchesne** [comment]
We are good to close this - executor definitely was not to blame.
