### ISSUE TITLE
Unable to configure client using with gofig package

### ISSUE THREAD

**Issue by vladimirvivien** [emccode/libstorage#215]
I am configuring the config object to initialize a libStorage client as follows:
```
config := gofig.NewRegistration("libstorage")
config.Key(gofig.String, "", "127.0.0.1:7981", "", "libstorage.host")
gofig.Register(config)
client, err := client.New(ctx, gofig.New())
```
This generates error `invalid address`

Is there a way to programmatically build the config needed without creating a yaml string ?

PS: I also tried the following and yields the same result.
```
cfg := gofig.New()
cfg.Set("libstorage.host", "127.0.0.1:7981")
client, err := client.New(ctx, cfg)
```

**Comment by clintonskitson** [comment]
@vladimirvivien Is that exactly the address that you have in your config file? If I recall that must be a valid URI which would translate to `tcp://127.0.0.1:7981`.

**Comment by akutz** [comment]
A valid Golang network address to be specific. See https://golang.org/pkg/net/. You combine the protocol with the address.

Also, the first way you tried is incorrect. That's for registering a config, not creating an instance to be used. Your second attempt is the correct way to do it.

**Comment by vladimirvivien** [comment]
@clintonskitson thanks. I realize i was leaving out the network.

**Comment by vladimirvivien** [comment]
@akutz thanks for clarifying how to use gofig.
