### ISSUE TITLE
AWS/EBS driver should gather instance/region details via client executor and not storage driver

### ISSUE THREAD

**Issue by cduchesne** [emccode/libstorage#279]
The EBS storage driver should not depend on any region / availability zone and should instead respect the client's availability zone. The storage driver has the ability to manage volumes outside of its own region/az, therefore the storage driver should be able to do management operations on any volumes in AWS EBS. Also, the client should only see volumes it could potentially access, which requires the volumes to be in the same availability zone.

EBS client executor gets following details:
https://github.com/emccode/libstorage/blob/master/drivers/storage/ebs/executor/ebs_executor.go#L61

EBS storage driver gets and assumes region details from its own perspective:
https://github.com/emccode/libstorage/blob/master/drivers/storage/ebs/storage/ebs_storage.go#L1027

The client executor should be gathering the full instance identity document and pass it to the storage driver.

**Comment by akutz** [comment]
Closed with #284, #285, #287, #286, #283, #282
