### ISSUE TITLE
go-bindata missing full path

### ISSUE THREAD

**Issue by clintonskitson** [emccode/libstorage#28]
https://github.com/emccode/libstorage/blob/master/Makefile#L359

I am wondering if there is a full path missing for go-bindata?

**Comment by akutz** [comment]
Hi @clintonskitson,

Please see the `.travis.yml` file for the answer on how to install the forked version of go-bindata:

```
GBD_GIT=https://github.com/akutz/go-bindata.git; GBD_DIR=$GOPATH/src/github.com/jteeuwen/go-bindata; mkdir -p $GBD_DIR && cd $GBD_DIR && git clone $GBD_GIT . && git checkout feature/md5checksum && go install ./... && cd -
```
